/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "capillaryGrinder_menu.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "CapillaryGrinder", "5dfce237-d428-470a-aa66-36a7f5931a23" };
AvrEeprom glAvrRom;
LiquidCrystal lcd(0, 1, 2, 4, 5, 6, 7);
LiquidCrystalRenderer renderer(lcd, 16, 2);

// Global Menu Item declarations
AnyMenuInfo minfoFaceChip = { "Face Chip", 4, 0xffff, 0, startFaceChip };
ActionMenuItem menuFaceChip(&minfoFaceChip, nullptr, INFO_LOCATION_RAM);
AnyMenuInfo minfoFaceCapillary = { "Face Capillary", 3, 0xffff, 0, startFaceCapillary };
ActionMenuItem menuFaceCapillary(&minfoFaceCapillary, &menuFaceChip, INFO_LOCATION_RAM);
AnyMenuInfo minfoGrindCapillary = { "Grind Capillary", 2, 0xffff, 0, startGrind };
ActionMenuItem menuGrindCapillary(&minfoGrindCapillary, &menuFaceCapillary, INFO_LOCATION_RAM);
AnyMenuInfo minfoCalibrateZero = { "Zero", 6, 0xffff, 0, setZero };
ActionMenuItem menuCalibrateZero(&minfoCalibrateZero, nullptr, INFO_LOCATION_RAM);
AnyMenuInfo minfoCalibrateOffset = { "Offset", 5, 2, 0, setOffset };
EditableLargeNumberMenuItem menuCalibrateOffset(&minfoCalibrateOffset, LargeFixedNumber(4, 0, 0U, 0U, false), true, &menuCalibrateZero, INFO_LOCATION_RAM);
SubMenuInfo minfoCalibrate = { "Calibrate", 1, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackCalibrate(&minfoCalibrate, &menuCalibrateOffset, INFO_LOCATION_RAM);
SubMenuItem menuCalibrate(&minfoCalibrate, &menuBackCalibrate, &menuGrindCapillary, INFO_LOCATION_RAM);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(true);
    menuMgr.setEepromRef(&glAvrRom);
    // Code generated by plugins.
    Wire.begin();
    lcd.setIoAbstraction(ioFrom8574(0x27, 0xff, &Wire));
    lcd.begin(16, 2);
    renderer.setUpdatesPerSecond(10);
    lcd.configureBacklightPin(3);
    lcd.backlight();
    switches.init(internalDigitalIo(), SWITCHES_POLL_EVERYTHING, true);
    menuMgr.initForUpDownOk(&renderer, &menuCalibrate, 3, 2, 8, 20);
}

